# Type labels
- name: "type:feature"
  color: "0E8A16"
  description: "New functionality being added to the application"
- name: "type:bug"
  color: "D73A4A"
  description: "Something isn't working as expected"
- name: "type:enhancement"
  color: "A2EEEF"
  description: "Improvement to existing features or functionality"
- name: "type:documentation"
  color: "0075CA"
  description: "Improvements or additions to documentation"
- name: "type:task"
  color: "FBCA04"
  description: "General tasks, maintenance, or chores"
- name: "type:question"
  color: "CC317C"
  description: "Further information is requested or required"

# Priority labels
- name: "priority:critical"
  color: "B60205"
  description: "P0 issues that must be fixed immediately"
- name: "priority:high"
  color: "D93F0B"
  description: "P1 issues with high importance"
- name: "priority:medium"
  color: "FBCA04"
  description: "P2 issues with medium importance"
- name: "priority:low"
  color: "0E8A16"
  description: "P3 issues that are nice to have"

# Component labels
- name: "component:eventmanagement"
  color: "5319E7"
  description: "Related to event creation, management, and execution"
- name: "component:datecoordination"
  color: "1D76DB"
  description: "Related to date suggestion, voting, and scheduling"
- name: "component:archive"
  color: "006B75"
  description: "Related to presentation archive functionality"
- name: "component:contentmanagement"
  color: "FBCA04"
  description: "Related to content creation and management"
- name: "component:infrastructure"
  color: "C5DEF5"
  description: "Related to development infrastructure, CI/CD, etc."
- name: "component:ui"
  color: "BFD4F2"
  description: "Related to user interface elements"
- name: "component:auth"
  color: "D4C5F9"
  description: "Related to authentication and authorization"
- name: "component:api"
  color: "0E8A16"
  description: "Related to API functionality"

# Status labels
- name: "status:backlog"
  color: "EEEEEE"
  description: "Not yet started, in the backlog"
- name: "status:ready"
  color: "C2E0C6"
  description: "Ready for development"
- name: "status:inprogress"
  color: "0E8A16"
  description: "Currently being worked on"
- name: "status:review"
  color: "FBCA04"
  description: "Ready for review"
- name: "status:blocked"
  color: "D93F0B"
  description: "Blocked by another issue or external factor"

# Additional labels
- name: "good first issue"
  color: "7057FF"
  description: "Good for newcomers to the project"
- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"
- name: "duplicate"
  color: "CCCCCC"
  description: "This issue already exists"
- name: "wontfix"
  color: "FFFFFF"
  description: "This will not be worked on"
- name: "dependencies"
  color: "0366D6"
  description: "Pull requests that update a dependency file"