# GitHub Release設定
# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

changelog:
  categories:
    - title: 🚀 新機能
      labels:
        - enhancement
        - feature
        - feat
    - title: 🐛 バグ修正
      labels:
        - bug
        - fix
        - bugfix
    - title: 📚 ドキュメント
      labels:
        - documentation
        - docs
    - title: 🔧 リファクタリング
      labels:
        - refactor
        - refactoring
    - title: 🏗️ ビルド・CI/CD
      labels:
        - build
        - ci
        - workflow
        - automation
    - title: 🔒 セキュリティ
      labels:
        - security
        - vulnerability
    - title: ⚡ パフォーマンス
      labels:
        - performance
        - optimization
    - title: 🧪 テスト
      labels:
        - test
        - testing
    - title: 🎨 デザイン・UI/UX
      labels:
        - design
        - ui
        - ux
        - style
    - title: 🔄 その他の変更
      labels:
        - "*"

  exclude:
    labels:
      - dependencies
      - duplicate
      - question
      - invalid
      - wontfix
      - chore

    authors:
      - dependabot
      - github-actions

# Pull Request用テンプレート設定
pull_request_template: |
  ## 📝 変更内容

  <!-- このPRで行った変更内容を記述してください -->

  ## 🔗 関連Issue

  <!-- 関連するIssueがあれば記載してください -->
  Closes #

  ## ✅ チェックリスト

  - [ ] テストが通る
  - [ ] リンティングが通る
  - [ ] ドキュメントを更新した（必要に応じて）
  - [ ] Breaking changeがある場合、BREAKING CHANGEをコミットメッセージに含めた

  ## 🧪 テスト内容

  <!-- テスト方法や確認内容を記述してください -->

  ## 📸 スクリーンショット（UI変更がある場合）

  <!-- UI変更がある場合はスクリーンショットを添付してください -->

# Issue用テンプレート設定
issue_template:
  bug:
    name: 🐛 バグ報告
    description: バグや問題を報告する
    labels: ["bug"]
    body: |
      ## 🐛 問題の説明

      <!-- バグの概要を記述してください -->

      ## 🔄 再現手順

      1. 
      2. 
      3. 

      ## 📱 環境

      - OS: 
      - ブラウザ: 
      - WordPress バージョン: 
      - テーマバージョン: 

      ## 📸 スクリーンショット

      <!-- エラーの画面があれば添付してください -->

  feature:
    name: 🚀 機能リクエスト
    description: 新しい機能や改善を提案する
    labels: ["enhancement"]
    body: |
      ## 🚀 提案する機能

      <!-- 提案する機能の概要を記述してください -->

      ## 💡 理由・背景

      <!-- なぜこの機能が必要なのかを説明してください -->

      ## 📋 実装案

      <!-- 実装のアイデアがあれば記述してください -->

      ## ⚡ 追加情報

      <!-- その他の情報があれば記述してください -->
