version: '3.8'

services:
  wordpress-test:
    image: wordpress:6.4-php8.2-apache
    container_name: lt-wordpress-test
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mysql-test
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_test
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG', true);
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', false);
        define('SCRIPT_DEBUG', true);
    volumes:
      - wordpress_test_data:/var/www/html
      - ./lightningtalk-child-theme.zip:/tmp/lightningtalk-child-theme.zip
      - ./lightningtalk-safe-test.zip:/tmp/lightningtalk-safe-test.zip
      - ./cocoon-master.zip:/tmp/cocoon-master.zip:ro
    depends_on:
      - mysql-test

  mysql-test:
    image: mysql:8.0
    container_name: lt-mysql-test
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress_test
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_test_data:/var/lib/mysql

  wordpress-cli:
    image: wordpress:cli-php8.2
    container_name: lt-wp-cli
    depends_on:
      - wordpress-test
      - mysql-test
    environment:
      WORDPRESS_DB_HOST: mysql-test
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_test
    volumes:
      - wordpress_test_data:/var/www/html
    profiles:
      - cli

volumes:
  wordpress_test_data:
  mysql_test_data: