# Lightning Talk Circle - Local Development Environment
# Optimized for file-based storage and quick development setup

# version: '3.8'  # Removed as it's obsolete in modern Docker Compose

services:
  # Lightning Talk Application - Development Mode
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: lightningtalk-dev
    # Use uid:gid of current user to avoid permission issues
    user: "${DOCKER_UID:-1001}:${DOCKER_GID:-1001}"
    environment:
      NODE_ENV: development
      PORT: 3000
      # ファイルベースストレージのため、データベース設定は不要
      EMAIL_ENABLED: false
      DEBUG: true
      # GitHub API settings (optional for local development)
      GITHUB_TOKEN: ${GITHUB_TOKEN:-}
      GITHUB_OWNER: ${GITHUB_OWNER:-lightningtalk-circle}
      GITHUB_REPO: ${GITHUB_REPO:-main}
    ports:
      - "3010:3000" # メインアプリケーション
      - "9229:9229" # Node.js デバッグポート
    volumes:
      - .:/app
      - /app/node_modules
      - ./data:/app/data # データファイル永続化
      - ./logs:/app/logs # ログファイル永続化
      - ./server/data:/app/server/data # サーバーデータファイル永続化
    restart: unless-stopped
    command: npm run dev
    networks:
      - lightningtalk-local
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # WordPress Theme Development Environment (Optional)
  wordpress:
    image: wordpress:6.4-apache
    container_name: lightningtalk-wordpress
    environment:
      WORDPRESS_DB_HOST: wp-db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
    ports:
      - "8888:80"
    volumes:
      - ./wordpress:/var/www/html/wp-content/themes/lightningtalk-child
      - wp_data:/var/www/html
    depends_on:
      - wp-db
    restart: unless-stopped
    networks:
      - lightningtalk-local

  # MySQL for WordPress (separate from main app)
  wp-db:
    image: mysql:8.0
    container_name: lightningtalk-wp-db
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - wp_db_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - lightningtalk-local
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Modern WordPress Theme Development (Vite + React)
  modern-theme:
    build:
      context: ./lightningtalk-modern
      dockerfile: Dockerfile
    container_name: lightningtalk-modern
    environment:
      NODE_ENV: development
      VITE_DEV_SERVER_HOST: 0.0.0.0
      VITE_DEV_SERVER_PORT: 3001
    ports:
      - "3002:3001" # Vite dev server
      - "6006:6006" # Storybook
    volumes:
      - ./lightningtalk-modern:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - lightningtalk-local
    profiles:
      - modern # プロファイルで条件付き起動

  # Nginx Reverse Proxy (統合開発環境)
  nginx:
    image: nginx:alpine
    container_name: lightningtalk-nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/var/www/html/static:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - lightningtalk-local
    profiles:
      - full # プロファイルで条件付き起動

  # Tools Container for utilities
  tools:
    image: node:20-alpine
    container_name: lightningtalk-tools
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - lightningtalk-local
    profiles:
      - tools
    command: tail -f /dev/null # Keep container running

  # Initialize permissions for data directories
  init-permissions:
    image: alpine:latest
    container_name: lightningtalk-init-permissions
    user: "0:0" # Run as root to fix permissions
    volumes:
      - ./data:/host-data
      - ./logs:/host-logs
      - ./server/data:/host-server-data
    command:
      - sh
      - -c
      - |
        # Create directories if they don't exist
        mkdir -p /host-data /host-logs /host-server-data

        # Set ownership to the user that will run the app
        chown -R ${DOCKER_UID:-1001}:${DOCKER_GID:-1001} /host-data /host-logs /host-server-data

        # Set proper permissions
        chmod -R 755 /host-data /host-logs /host-server-data

        echo "Permissions initialized successfully"
    profiles:
      - init

volumes:
  wp_data:
    driver: local
  wp_db_data:
    driver: local

networks:
  lightningtalk-local:
    driver: bridge
    name: lightningtalk-local-network
