version: '3.8'

services:
  # Node.js application test
  app-test:
    build:
      context: .
      dockerfile: docker/Dockerfile.test
    container_name: lt_app_test
    environment:
      - NODE_ENV=test
      - PORT=3000
    command: |
      sh -c "
        npm run test:unit &&
        npm run test:integration &&
        echo 'All tests passed'
      "
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - test-network

  # WordPress test environment
  wordpress:
    image: wordpress:latest
    container_name: lt_wordpress_test
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
      - ./lightningtalk-child-theme.zip:/tmp/theme.zip:ro
    depends_on:
      - db
    networks:
      - test-network

  db:
    image: mysql:8.0
    container_name: lt_mysql_test
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - test-network

networks:
  test-network:
    driver: bridge

volumes:
  wordpress_data:
    driver: local
  db_data:
    driver: local
