services:
  wordpress:
    image: wordpress:latest
    container_name: lt_wordpress_test
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
      - ./dist/lightningtalk-wordpress-theme-v1.3.0.zip:/tmp/theme.zip
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: lt_mysql_test
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    command: 
      - '--default-authentication-plugin=mysql_native_password'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'

volumes:
  wordpress_data:
  db_data: