blank_issues_enabled: false
contact_links:
  - name: Lightning Talk Circle Documentation
    url: https://github.com/20m61/lightningtalk-circle/tree/main/docs
    about: Please review the project documentation before creating an issue.