name: Create Issue Labels

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "yes" to confirm creation of repository labels'
        required: true
        default: 'no'

jobs:
  create-labels:
    if: github.event.inputs.confirmation == 'yes'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Create labels
        uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml