name: Set Up Issue Labels

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "yes" to confirm setting up issue labels'
        required: true
        default: 'no'

jobs:
  setup-labels:
    if: github.event.inputs.confirm == 'yes'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up labels
        uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml
          prune: false